include: package:very_good_analysis/analysis_options.2.3.0.yaml
analyzer:
  exclude: [lib/protobufs/generated/*, analysis_options.yaml]
linter:
  rules:
    avoid_final_parameters: true
    avoid_multiple_declarations_per_line: true
    close_sinks: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    no_runtimeType_toString: true
    prefer_if_elements_to_conditional_expressions: false
    prefer_null_aware_operators: true
    public_member_api_docs: false
    require_trailing_commas: true
    sized_box_shrink_expand: true
    super_goes_last: true
    use_enums: true
    use_if_null_to_convert_nulls_to_bools: true
    use_setters_to_change_properties: false
    always_use_package_imports: true
